branches:
  only:
    - master

language: perl

perl:
  - "5.18"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y git
  - sudo apt-get install -y xsltproc
  - sudo apt-get install -y syslinux
  - sudo apt-get install -y syslinux-utils
  - sudo apt-get install -y tar

install:
    - cpanm -f -n $(cat .perlmodules | tr "\n" " ")

script: make TRAVISENV="-I /home/travis/perl5/lib/perl5" KIWI_NO_NET=1 KIWI_NO_FS=1 test
