branches:
  only:
    - master

language: perl

perl:
  - "5.18"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y git
  - sudo apt-get install -y xsltproc
  - sudo apt-get install -y syslinux
  - sudo apt-get install -y tar

install:
    - cpanm -f -n $(cat .perlmodules | tr "\n" " ")

script: make test
